package mypkg;

import java.util.InputMismatchException;
import java.util.Scanner;

/* 2. 
 * Write a Java application which, within the main() method, contains a squence of code that may throw various
 * exceptions, such as ArithmeticException, ArrayIndexOutOfBoundsException, NullPointerException,
 * NumberFormatException, as well as others which you consider to be useful for testing. In the catch block show the
 * corresponding message generated by these exceptions. The finally block just prints the message, "I may or may not have caught an exception".
 */

public class OvidiuGherman_Lab06_P02 {

	public static void main(String[] args) {		
		
		Scanner scanner = new Scanner(System.in);
		Integer n, number[] = null;
		System.out.print("Please enter the size of the array: ");
		try { 
			n = scanner.nextInt();
			number = new Integer[n + 1];
		} catch (InputMismatchException e) {
			System.out.println("Invalid input");		
		} finally { 
			System.out.println("I may or may not have caught an exception");
		}
		
		
		System.out.print("Please enter the values of the array: ");
		try {
			for(int i = 0; i < number.length - 1;i++) {
				number[i] = scanner.nextInt();
			}
		} catch(ArrayIndexOutOfBoundsException except) {
			System.out.println("Invalid index!");
		} catch(InputMismatchException except) {
			System.out.println("Invalid element");			
		} finally { 
			System.out.println("I may or may not have caught an exception");
		}
		
		String indexString;
		Integer indexInt;
		System.out.println("Please enter the index of a element: ");
		try { 
			scanner.nextLine();
			indexString = scanner.nextLine();
			indexInt = Integer.parseInt(indexString);
			System.out.print("The element at the position " + indexInt + " is: " + number[indexInt] + " ");		
			System.out.print("\nPlease enter a value that will divide the index: "); 
			int div = scanner.nextInt();
			System.out.print("The result of the division is: " + (indexInt / div));
			System.out.print("\nThe last element of the array is(size+1): " + number[number.length]);
		} catch(NumberFormatException except) {
			System.out.println("Parsing error!(Setting index to starting position)");
			indexInt = 0;
		} catch(ArrayIndexOutOfBoundsException except) {
			System.out.println("Invalid index");
		} catch(ArithmeticException except) { 
			System.out.println("Invalid expresion(Can not divide a number by 0)");
		} catch(InputMismatchException except) {
			System.out.println("Invalid element");			
		} catch(NullPointerException except) {
			System.out.println("Error!\nLast element of the array is null!");
		} finally { 
			System.out.println("I may or may not have caught an exception");
		}
		scanner.close();
	}

}
